server:
  port: 8081

spring:
  application:
    name: service-consumer
  redis:
    host: 10.5.1.2
    port: 6379
    password: 123456
    pool:
      max-idle: 300   # 连接池中的最大空闲连接
      max-wait: 3000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-active: 500 # 连接池最大连接数（使用负值表示没有限制）
      min-idle: 0     # 连接池中的最小空闲连接
    timeout: 5000     # 连接超时时间（毫秒）

eureka:
  client:
    service-url.defaultZone:  http://localhost:8761/eureka/

service:
  provider:
    name: SERVICE-PROVIDER

zuul:
  routes:
    apis:
      path: /api/**
      service-id: ${service.provider.name}

logging:
  level:
    com.bq.wms.admin.config.shiro.cache:  DEBUG





