server:
  port: 8081

spring:
  application:
    name: service-consumer


eureka:
  client:
    service-url.defaultZone:  http://localhost:8761/eureka/

service:
  provider:
    name: SERVICE-PROVIDER

zuul:
  routes:
    apis:
      path: /api/**
      service-id: ${service.provider.name}

